services:
  - type: web
    name: my-pet-center
    env: python
    buildCommand: "cd frontend && npm install && npm run build && cd .. && pip install -r backend/requirements.txt"
    startCommand: "uvicorn backend.app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: DATABASE_URL
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@mypetcenter.com
      - key: ADMIN_PHONE
        value: "01200888841"
      - key: ADMIN_PASSWORD
        sync: false
